# Generated by Django 5.2.17 on 2026-08-24 10:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=40)),
                ('match_id', models.UUIDField(blank=True, null=True)),
                ('room_id', models.UUIDField(blank=True, null=True)),
                ('properties', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
                'indexes': [models.Index(fields=['event_type', 'occurred_at'], name='analytics_a_event_t_69a889_idx')],
            },
        ),
    ]
