# Generated by Django 5.2.17 on 2026-08-24 08:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("finished", "Finished"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("rules", models.JSONField()),
                ("started_at", models.DateTimeField()),
                ("deadline", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("latest_sequence", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="result",
                        serialize=False,
                        to="matches.match",
                    ),
                ),
                ("outcome", models.CharField(max_length=20)),
                ("reason", models.CharField(max_length=20)),
                ("winner_participant_ids", models.JSONField(default=list)),
                ("secret_revealed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("protected_secret", models.TextField(editable=False)),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge",
                        to="matches.match",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("display_name", models.CharField(max_length=20)),
                ("avatar_id", models.CharField(max_length=50)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                (
                    "solve_state",
                    models.CharField(
                        choices=[
                            ("playing", "Playing"),
                            ("solved", "Solved"),
                            ("unsolved", "Unsolved"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="playing",
                        max_length=20,
                    ),
                ),
                ("solved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participations",
                        to="accounts.guestidentity",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="matches.match",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("command_id", models.UUIDField()),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("ordinal", models.PositiveIntegerField()),
                ("guess", models.CharField(max_length=6)),
                ("feedback", models.JSONField()),
                ("solved", models.BooleanField(default=False)),
                ("accepted_at", models.DateTimeField()),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="matches.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["ordinal"],
            },
        ),
        migrations.CreateModel(
            name="CommandRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("command_id", models.UUIDField()),
                ("operation", models.CharField(max_length=40)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="accounts.guestidentity",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="matches.match",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("guest", "command_id"), name="unique_guest_command"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(
                fields=("match", "guest"), name="unique_match_guest"
            ),
        ),
        migrations.AddConstraint(
            model_name="attempt",
            constraint=models.UniqueConstraint(
                fields=("participant", "command_id"), name="unique_participant_command"
            ),
        ),
        migrations.AddConstraint(
            model_name="attempt",
            constraint=models.UniqueConstraint(
                fields=("participant", "ordinal"), name="unique_participant_ordinal"
            ),
        ),
    ]
