# Generated by Django 5.2.17 on 2026-08-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0002_match_finish_due_at_participant_connected_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="state",
            field=models.CharField(
                choices=[
                    ("countdown", "Countdown"),
                    ("active", "Active"),
                    ("finishing", "Finishing"),
                    ("finished", "Finished"),
                    ("abandoned", "Abandoned"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
