# Generated by Django 5.2.17 on 2026-08-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_challenge_committed_at_challenge_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='secret_destroyed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
