# Generated by Django 5.2.17 on 2026-09-16 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_challenge_secret_destroyed_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='challenge',
            name='unique_shared_match_challenge',
        ),
        migrations.AddField(
            model_name='attempt',
            name='round_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='challenge',
            name='round_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_matches', to='matches.participant'),
        ),
        migrations.AddField(
            model_name='match',
            name='round_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='round_state',
            field=models.CharField(default='active', max_length=30),
        ),
        migrations.AddField(
            model_name='match',
            name='total_rounds',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='round_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='round_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='room_mode',
            field=models.CharField(default='party', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='rounds_count',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddConstraint(
            model_name='challenge',
            constraint=models.UniqueConstraint(condition=models.Q(('solver__isnull', True)), fields=('match', 'round_number'), name='unique_shared_match_challenge'),
        ),
    ]
