# Generated by Django 5.2.17 on 2026-09-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_remove_challenge_unique_shared_match_challenge_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attempt',
            name='unique_participant_ordinal',
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(fields=('participant', 'round_number', 'ordinal'), name='unique_participant_round_ordinal'),
        ),
    ]
