# Generated by Django 5.2.17 on 2026-09-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_remove_attempt_unique_participant_ordinal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_mode',
            field=models.CharField(choices=[('duel', 'Duel'), ('party', 'Party')], default='duel', max_length=20),
        ),
    ]
