# Generated by Django 5.2.17 on 2026-09-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_alter_result_reason'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='matchevent',
            index=models.Index(condition=models.Q(('published_at__isnull', True)), fields=['next_attempt_at'], name='matchevent_outbox_due_idx'),
        ),
        migrations.AddIndex(
            model_name='roomevent',
            index=models.Index(condition=models.Q(('published_at__isnull', True)), fields=['next_attempt_at'], name='roomevent_outbox_due_idx'),
        ),
    ]
